name: trRNA2
channels:
  - https://conda.rosettacommons.org
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - numpy=2.1.2
  - python=3.10
  - pyrosetta=2024.39+release.59628fb
  - sympy=1.13.1
  - cudatoolkit=11.8
  - pytorch::pytorch=2.5.1=py3.10_cuda11.8_cudnn9.1.0_0
  - pytorch::torchaudio=2.5.1=py310_cu118
  - pytorch::torchvision=0.20.1=py310_cu118
  - tqdm
  - pip
  - pip:
      - absl-py==2.1.0
      - biopython==1.85
      - dm-tree==0.1.9
      - einops==0.8.1
      - ml-collections==1.0.0
      - scipy==1.15.2
      - torch-geometric==2.6.1